import type { Metadata } from 'next';
import { Catamaran } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/providers';
import { Nav } from '@/modules';
import Script from 'next/script';
import { Container } from '@/components';

const catamaran = Catamaran({
	weight: ['400', '500', '600', '700', '800', '900'],
	style: ['normal'],
	variable: '--font-catamaran',
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Kenny Krosky',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.png" />
			</head>
			<body className={catamaran.className}>
				<ThemeProvider>
					<Nav />
					<div className="py-20 md:py-24"></div>
					<main>{children}</main>
					<footer className="border-t py-10 mt-20">
						<Container>
							<p className="text-center text-sm text-gray-500">
								&copy; {new Date().getFullYear()} Kenny Krosky.
								All rights reserved.
							</p>
						</Container>
					</footer>
				</ThemeProvider>
			</body>
		</html>
	);
}
